package com.foo.jason.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "user")
public class User {

	@Id
	@GeneratedValue
	@Column(name = "userId", unique = true, nullable = false)
	private Integer	userId;

	@Column(name = "firstName", nullable = false, length = 50)
	private String	firstName;

	@Column(name = "lastName", nullable = false, length = 50)
	private String	lastName;

	// Constructors < no argument - all arguments except id - all arguments >
	public User() {
		super();
		this.userId = null;
		this.firstName = null;
		this.lastName = null;
	}

	public User(String firstName, String lastName) {
		super();
		this.userId = null;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public User(Integer userId, String firstName, String lastName) {
		super();
		this.userId = userId;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	// Autogenerated Getters and Setters
	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastname() {
		return lastName;
	}

	public void setLastname(String lastName) {
		this.lastName = lastName;
	}

	@Override
	public String toString() {
		return "User [userId=" + userId + ", firstName=" + firstName + ", lastName=" + lastName + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((firstName == null) ? 0 : firstName.hashCode());
		result = prime * result + ((lastName == null) ? 0 : lastName.hashCode());
		result = prime * result + ((userId == null) ? 0 : userId.hashCode());
		return result;
	}

	/**
	 * equals() is useful for junit tests
	 * 
	 * @author jason
	 * @param obj
	 *            : object to compare with this
	 * @return true if obj==this, false if obj!=this
	 */
	@Override
	public boolean equals(Object obj) {
		User other = (User) obj;
		if (getClass() == obj.getClass() && userId.equals(other.getUserId()) && firstName.equals(other.getFirstName())
			&& lastName.equals(other.getLastname()))
			return true;
		else
			return false;
	}
}